### ISSUE TITLE
App Methods

### ISSUE THREAD

**Issue by jlag34** [miller2676/jamming#1]
You did a good job on your most of your methods in your App.js file. The only one I had a problem with is `addTrack`. On line 30-31 you did:

```
let tracks = this.state.playlistTracks;
tracks.push(track);
```

This will mutate state because the first line does not return a new copy of `playlistTracks`. It is a direct reference to state. Therefore, when you push to `tracks` that's the same as pushing to `this.state.playlistTracks` which mutates state because it is happening outside of `setState`.

**Comment by mel-miller** [comment]
Corrected by creating a copy of the array using slice()
`let tracks = this.state.playlistTracks.slice();`
