### ISSUE TITLE
Summary - Meets Expectations

### ISSUE THREAD

**Issue by jlag34** [miller2676/jamming#4]
You did a really nice job with your project. Great job making it through all of the Spotify.js work. Also, you showed that you understand the basics of React like reusing components, rending child components, passing props, and updating state. Just make sure you watch out for mutating state. For more information on that try googling `JavaScript value vs reference`. All in all, good job on this one!

**Comment by mel-miller** [comment]
@jlag34 - Thanks for the feedback.
